## Expressed genes of single cell data

library(nichenetr)


## 
mtx_wo_SMC <- mtx_wo_SMC[["RNA"]]@counts %>% as.matrix() %>% t()
dim(mtx_wo_SMC) #18478   191



# Define expressed genes in sender and receiver cell populations
# https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md

fun.expressed.genes <- function(MTX){
  expressed_genes <- 
    MTX %>% 
    apply(2,function(x){10*(2**x - 1)}) %>% 
    apply(2,function(x){log2(mean(x) + 1)}) %>% 
    .[. >= 4] %>% 
    names()
  return(expressed_genes)
}
## To determine expressed genes in this case study, we use the definition used by Puram et al. (the authors of this dataset), which is: Ea, the aggregate expression of each gene i across the k cells, calculated as Ea(i) = log2(average(TPM(i)1…k)+1), should be >= 4. We recommend users to define expressed genes in the way that they consider to be most appropriate for their dataset. For single-cell data generated by the 10x platform in our lab, we don’t use the definition used here, but we consider genes to be expressed in a cell type when they have non-zero values in at least 10% of the cells from that cell type.


# Define expressed genes in 10X data set
# https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md
## receiver
receiver = "CD8 T"
expressed_genes_receiver = 
  get_expressed_genes(receiver, seuratObj, pct = 0.10)


